const SERVERERROR = {
    CODE: 500,
    MESSAGE: 'DB_ERROR',
};

const SUCCESSCODE = {
    STANDARD: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NOCONTENT: 204,
};


const CLIENTSIDEERROR = {
    NOTFOUNDCODE: 404,
    ALREADYEXISTCODE: 409,
    BADREQUESTCODE: 400
}

module.exports = {
    SUCCESSCODE,
    SERVERERROR,
    CLIENTSIDEERROR
};